### ISSUE TITLE
Not the latest EA file

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/uml-models#2]
The EA files online in this repository (https://github.com/INSPIRE-MIF/uml-models/blob/main/approved/ea%2Bxmi/EAXMI.zip) and on https://inspire.ec.europa.eu/Data-Models/Data-Specifications/2892 are not the latest ones that were used to derive the GML application schemas.

See e.g. for Administrative Units:

![image](https://user-images.githubusercontent.com/11427611/174623105-2586d200-8e45-4749-a3a9-8c02d3196845.png)

The latest version (earlier available via https://inspire-twg.jrc.ec.europa.eu/svn/inspire-model/branches/public/approved/latest) should contain the following:

![image](https://user-images.githubusercontent.com/11427611/174622785-e5bd983c-f6ae-48c4-8d6f-d5df6aa23d0c.png)

**Comment by sMorrone** [comment]
Dear @heidivanparys thank you for spotting this.
If I get you well, an updated version of the EA files exists, though currently not accessible. In this case, having access to it would avoid the need to redo work already done. @MarcoMinghini maybe you can help on this? is it possible to get the updated EA project file?
thank you

**Comment by fabiovinci** [comment]
Dear all,

we checked all the EA projects available and in the end, we decided to start from the current one introducing all the needed changes.

Below is the full list of changes:

- Updated all the "targetNamespace" and "version" tags in the properties of the Application Schema folders
- Removed application schema "Safety" for the HH data theme since it is draft
- Removed application schemas "Protected Sites Full" and "Protected Sites Natura2000" since they are draft
- Renamed application schemas "Protected Sites Simple" to "Protected Sites"
- Added missed application schemas "ElevationTIN"

The updated EA project will be included in the 2022.2 release.

**Comment by fabiovinci** [comment]
The updated EA project has been included in the 2022.2 release.
